version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - PORT
      - SECRET_AUTH_KEY
      - APP_MODE
      - HIDE_POST_ENDPOINTS
      - DATABASE_URL
    depends_on:
      db:
        condition: service_started
    entrypoint:
      [
        "sh",
        "-c",
        "npx prisma migrate deploy && npm run start:prod"
      ]

  db:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
