version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fzrsahi
      POSTGRES_PASSWORD: fzrsahi123
      POSTGRES_DB: me
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
